#!/usr/bin/env Rscript
# Derives each ratio trait's heritability and its genetic correlation with
# CH4 from its component traits' bivariate (co)variances with CH4, instead
# of (or alongside) fitting the ratio itself as a single ASReml trait.
# docs/revision_plan.md Section 5, step 7.
#
# Method: first-order Taylor linearisation of a ratio R = X/Y around the
# observed trait means (mu_X, mu_Y):
#   R \approx mu_X/mu_Y + (1/mu_Y)(X - mu_X) - (mu_X/mu_Y^2)(Y - mu_Y)
# so R is treated as the linear combination a'v with v = (X, Y) and
# gradient a = (1/mu_Y, -mu_X/mu_Y^2). Then Var(R) = a' Sigma a for any
# (co)variance matrix Sigma of (X, Y) -- applied here once with the
# genetic (co)variance matrix (giving Var_A(R)) and once with the
# phenotypic (co)variance matrix (giving Var_P(R)), and h2(R) =
# Var_A(R)/Var_P(R). Cov_A(CH4, R) = a' Sigma_A[, "CH4"] gives the genetic
# correlation with CH4 the same way.
#
# This is NOT a new derivation: it is the identical gradient (up to an
# irrelevant overall sign -- the source uses it for a "minimise CH4/LW"
# breeding-objective direction, hence its -1/mu_Y; h2/rg here use the
# natural R = X/Y sign instead) already used for real in the upstream
# selection-index repo, commit fb1f0a2cddb82ba322cfd86b4ad3d99830385a44:
#   ~/Methane_Selection_Index_Analysis/index_weight_methane.R:111-116
#   ~/Methane_Selection_Index_Analysis/MC_weight.R:169-174
# (dermok1010/Methane_Selection_Index_Analysis, read-only reference per
# this repo's CLAUDE.md -- not vendored, not modified).
#
# Inputs: results/bivariate_summary.csv rows for the six `methane_<component>`
# pairs generated by `01_generate_models.R --set=components` (sigma_ped_*/
# sigma_res_*/sigma_ide -- see that script and 03_parse_results.R for their
# exact meaning), plus each component's raw sample mean computed directly
# from data/phenotype_asreml.csv (the Taylor expansion point, matching the
# "around observed trait means" convention already used upstream).
#
# ch4_ratio = CH4/(CH4+CO2) is a special case: its denominator Y = CH4+CO2
# is a sum, not a single fitted trait, so its Y-side (co)variances are
# first assembled from the methane_co2 bivariate fit (Var(Y) = VA_CH4 +
# VA_CO2 + 2*CovA(CH4,CO2); Cov(CH4,Y) = VA_CH4 + CovA(CH4,CO2)) before
# applying the same ratio gradient.

suppressPackageStartupMessages({})

pipeline_root <- normalizePath(
  file.path(dirname(sub("--file=", "", grep("--file=", commandArgs(), value = TRUE))), ".."),
  mustWork = FALSE
)
if (!dir.exists(file.path(pipeline_root, "results"))) pipeline_root <- getwd()

results_dir <- file.path(pipeline_root, "results")
bi_path <- file.path(results_dir, "bivariate_summary.csv")
if (!file.exists(bi_path)) {
  stop("results/bivariate_summary.csv not found -- run scripts/03_parse_results.R ",
       "on HPC output for the --set=components models first (see this repo's ",
       "asreml_pipeline/README.md workflow section).")
}
bi <- read.csv(bi_path, stringsAsFactors = FALSE)

phenotype_path <- file.path(pipeline_root, "data", "phenotype_asreml.csv")
pheno <- read.csv(phenotype_path)

# Ratio traits and their denominator's component-set code + phenotype column.
# "sum_with" marks ch4_ratio's special CH4+CO2 denominator case.
ratio_defs <- list(
  ch4ratio  = list(component = "co2",    variable = "co2_g_day2_1v3", sum_with_ch4 = TRUE,
                    label = "CH4 ratio = CH4/(CH4+CO2)"),
  ch4mbw    = list(component = "mbw",    variable = "Metabolic_BW",  sum_with_ch4 = FALSE,
                    label = "CH4/MBW"),
  ch4adg    = list(component = "adg",    variable = "adg",           sum_with_ch4 = FALSE,
                    label = "CH4/ADG"),
  ch4muscle = list(component = "muscle", variable = "ct_muscle_kg",  sum_with_ch4 = FALSE,
                    label = "CH4/MM"),
  ch4rumen  = list(component = "rumen",  variable = "rumen",         sum_with_ch4 = FALSE,
                    label = "CH4/rumen"),
  ch4lw     = list(component = "weight", variable = "weight",        sum_with_ch4 = FALSE,
                    label = "CH4/LW")
)

mu_ch4 <- mean(pheno$ch4_g_day2_1v3, na.rm = TRUE)

get_pair <- function(component) {
  row <- bi[bi$pair == paste0("methane_", component), ]
  if (nrow(row) == 0) {
    stop("No bivariate_summary.csv row for pair 'methane_", component, "' -- ",
         "was --set=components generated, run on HPC, and parsed?")
  }
  if (nrow(row) > 1) stop("Multiple rows for pair 'methane_", component, "' -- unexpected.")
  row
}

# Var_A/Var_P of R=X/Y and Cov_A(CH4,R) from a bivariate (CH4=X, component=Y)
# fit row, given mu_X, mu_Y. Sigma matrices are (X,Y); PE handling matches
# 03_parse_results.R's own convention exactly (vp_i includes sigma_ide,
# but the phenotypic covariance does not -- ide(ANI_ID) is a single shared,
# not trait-specific, PE term per config/models.yaml's random_effects
# comment, so it contributes to each trait's own variance but has no
# separately-estimated covariance term to add).
derive_ratio_stats <- function(row, mu_x, mu_y) {
  VA_X <- row$sigma_ped_1; VA_Y <- row$sigma_ped_2; CovA_XY <- row$sigma_ped_c
  VE_X <- row$sigma_res_1; VE_Y <- row$sigma_res_2; CovE_XY <- row$sigma_res_c
  VP_X <- row$sigma_ide + VE_X + VA_X
  VP_Y <- row$sigma_ide + VE_Y + VA_Y
  CovP_XY <- CovE_XY + CovA_XY

  a <- c(1 / mu_y, -mu_x / mu_y^2)
  quad <- function(v11, v12, v22) a[1]^2 * v11 + 2 * a[1] * a[2] * v12 + a[2]^2 * v22

  VA_R <- quad(VA_X, CovA_XY, VA_Y)
  VP_R <- quad(VP_X, CovP_XY, VP_Y)
  # Cov_A(CH4, R) = Cov_A(X, a1*X + a2*Y) = a1*VA_X + a2*CovA_XY
  CovA_CH4_R <- a[1] * VA_X + a[2] * CovA_XY

  list(VA_R = VA_R, VP_R = VP_R, h2_R = VA_R / VP_R,
       rg_ch4_R = CovA_CH4_R / sqrt(VA_X * VA_R))
}

results <- lapply(names(ratio_defs), function(code) {
  def <- ratio_defs[[code]]
  row <- get_pair(def$component)
  mu_component <- mean(pheno[[def$variable]], na.rm = TRUE)

  if (def$sum_with_ch4) {
    # Y = CH4 + component (ch4_ratio only). Assemble Y's (co)variances
    # from the CH4-component bivariate fit before applying the ratio
    # gradient, per this script's header.
    VA_X <- row$sigma_ped_1; VA_C <- row$sigma_ped_2; CovA_XC <- row$sigma_ped_c
    VE_X <- row$sigma_res_1; VE_C <- row$sigma_res_2; CovE_XC <- row$sigma_res_c
    row_y <- list(
      sigma_ped_1 = VA_X, sigma_ped_2 = VA_X + VA_C + 2 * CovA_XC, sigma_ped_c = VA_X + CovA_XC,
      sigma_res_1 = VE_X, sigma_res_2 = VE_X + VE_C + 2 * CovE_XC, sigma_res_c = VE_X + CovE_XC,
      sigma_ide = row$sigma_ide  # shared PE term unaffected by the sum
    )
    mu_y <- mu_ch4 + mu_component
    stats <- derive_ratio_stats(row_y, mu_ch4, mu_y)
  } else {
    stats <- derive_ratio_stats(row, mu_ch4, mu_component)
  }

  data.frame(ratio_trait = code, label = def$label, component_pair = paste0("methane_", def$component),
             convergence = row$convergence, mu_ch4 = mu_ch4, mu_component = mu_component,
             VA_R_derived = stats$VA_R, VP_R_derived = stats$VP_R,
             h2_derived = stats$h2_R, rg_ch4_derived = stats$rg_ch4_R,
             stringsAsFactors = FALSE)
})
results <- do.call(rbind, results)

# Cross-check against the direct single-trait fits, if available (both are
# optional here -- this script's job is to compute the component-derived
# side regardless of whether the direct-fit sweep has been parsed yet).
uni_path <- file.path(results_dir, "univariate_summary.csv")
direct_bi_path <- file.path(results_dir, "bivariate_summary.csv")
if (file.exists(uni_path)) {
  uni <- read.csv(uni_path, stringsAsFactors = FALSE)
  results$h2_direct <- uni$h2[match(results$ratio_trait, uni$trait_code)]
} else {
  results$h2_direct <- NA_real_
  message("results/univariate_summary.csv not found -- h2_direct left NA. ",
          "(Direct-fit comparison is optional; this script's own output does not depend on it.)")
}
results$rg_ch4_direct <- sapply(results$ratio_trait, function(code) {
  cand <- bi$pair[bi$pair %in% c(paste0("methane_", code), paste0("ch4_", code))]
  if (length(cand) == 1) bi$rg[bi$pair == cand] else NA_real_
})
results$h2_agree <- abs(results$h2_derived - results$h2_direct) < 0.02
results$rg_agree <- abs(results$rg_ch4_derived - results$rg_ch4_direct) < 0.05

out_path <- file.path(results_dir, "ratio_from_components.csv")
write.csv(results, out_path, row.names = FALSE)

cat("\n=============== RATIO TRAITS DERIVED FROM COMPONENT (CO)VARIANCES ===============\n")
print(results[, c("ratio_trait", "label", "convergence", "h2_derived", "h2_direct",
                   "h2_agree", "rg_ch4_derived", "rg_ch4_direct", "rg_agree")], digits = 4)
cat("\nWritten to", out_path, "\n")
if (any(!is.na(results$h2_agree) & !results$h2_agree)) {
  cat("\nWARNING: h2_derived vs h2_direct disagree (>0.02) for:",
      paste(results$ratio_trait[!is.na(results$h2_agree) & !results$h2_agree], collapse = ", "), "\n")
}
