!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
ch4_stage_het_residual -- A3 sensitivity model, generated by hand from
the pipeline's own univariate template (see
analysis/diagnostics/reviewer_a2_a3/02_prepare_stage_phenotype.R for the
data prep). Reviewer action plan A3: does allowing CH4's residual
variance to differ between young (age<2) and mature (age>=2) animals
materially change VA/PE/h2/repeatability vs the pooled model
(analysis/revision/asreml_pipeline/models/a_uni_methane.as)?
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1
 stage * !A

pedigree.csv.SRT
phenotype_asreml_stage.csv !SKIP 1 !MVINCLUDE

ch4_g_day2_1v3 ~ mu SEX TX BR SU CL CV LY UN het rec REARING_RANK BIRTH_RANK ewe_birth_rank ewe_rearing_rank age_in_weeks dam_parity_group_num ch4_GroupNumber !r ped(ANI_ID) ide(ANI_ID)
residual sat(stage).idv(units)

VPREDICT !DEFINE
# Discovery-only, same discipline as the PE-sensitivity variants
# (analysis/revision/asreml_pipeline/scripts/01_generate_models.R's
# gen_bivariate_pe_sensitivity header comment): sat(stage).idv(units)
# is a new residual structure for this pipeline, so its VPREDICT index
# numbering is not assumed -- read the real names/numbers off the .pvc
# output first, per ASReml-4.2-Functional-Specification.pdf Section
# 13.2, before writing any h2/repeatability/variance-ratio block.
