!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
bivariate_bi_ch4ratio_ch4ratiomol -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1
 stage_660 * !A
 ch4_young 1
 ch4_old 1
 cg_mean_cl * !A
 ch4_ratio_mol 1

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE

ch4_ratio ch4_ratio_mol ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber !r Trait.ped(ANI_ID) ide(ANI_ID)

# NOTE: independent PE not used for ch4ratio_ch4ratiomol -- no CONVERGED univariate ide(ANI_ID) estimate on file for ch4ratiomol in results/univariate_summary.csv. Falling back to the legacy shared ide(ANI_ID) term.
# No matching legacy bi_*.as file found for this pair -- no tuned
# starting values available. ASReml will auto-initialize this
# Trait.ped(ANI_ID) US structure from the data. If convergence is
# poor, consider bootstrapping starting values with !MAXIT 0 (see
# ASReml-4.2-Functional-Specification.pdf Section 5.8) and rerunning
# with !CONTINUE 2 (!TSV).

VPREDICT !DEFINE
P Vp1 1 2 5
P Vp2 1 4 7
P Cp 3 6
H h2_1 5 Vp1
H h2_2 7 Vp2
R rg 5 6 7
R re 2 3 4
R cp Vp1 Cp Vp2

