!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
bivariate_bi_ch4rmtmbwco2_mbw -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1
 stage_660 * !A
 ch4_young 1
 ch4_old 1
 cg_mean_cl * !A

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE

ch4_adj_MBW_co2 Metabolic_BW ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber !r Trait.ped(ANI_ID) diag(Trait !INIT 2.56623 1.91896).ide(ANI_ID)

1 2 1
0
Trait 0 US 1 0 9.5 !GP
Trait.ped(ANI_ID)
Trait 0 US 1.2 0 2.4 !GP
ANI_ID

VPREDICT !DEFINE
# Discovery-only VPREDICT: no derived quantities yet. Per
# ASReml-4.2-Functional-Specification.pdf Section 13.2, a bare
# VPREDICT !DEFINE + blank line reports every parameter's real
# name and number in the .pvc file -- read those off before
# writing any h2/SE block for this changed model structure.

