!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
bivariate_methane_adg -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE

ch4_g_day2_1v3 adg ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber !r us(Trait !INIT 3.91959 0 0.000587469 !GP).ped(ANI_ID) ide(ANI_ID)

# Functional-syntax !INIT starting values used instead of a legacy
# structure block -- see uni_ped_sigma/functional_init_pairs comment
# above this function for the full explanation. Starting values are
# in the model line itself (us(Trait !INIT ...)), not here.

VPREDICT !DEFINE
P Vp1 1 2 5
P Vp2 1 4 7
P Cp 3 6
H h2_1 5 Vp1
H h2_2 7 Vp2
R rg 5 6 7
R re 2 3 4
R cp Vp1 Cp Vp2
# CH4/ADG (delta-method SE via ASReml VPREDICT, see composite_vpredict_specs)
P caa1 5 * 29.88687532
P caa2 6 * -5850.750901
P caa3 7 * 286340.4566
P caVA caa1 + caa2 + caa3
P cap1 Vp1 * 29.88687532
P cap2 Cp * -5850.750901
P cap3 Vp2 * 286340.4566
P caVP cap1 + cap2 + cap3
H ca_h2 caVA caVP
# RMTADG (delta-method SE via ASReml VPREDICT, see composite_vpredict_specs)
P rtaa1 5 * 1
P rtaa2 6 * -5.984
P rtaa3 7 * 8.952064
P rtaVA rtaa1 + rtaa2 + rtaa3
P rtap1 Vp1 * 1
P rtap2 Cp * -5.984
P rtap3 Vp2 * 8.952064
P rtaVP rtap1 + rtap2 + rtap3
H rta_h2 rtaVA rtaVP

