!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
bivariate_bi_methane_ch4mbw_cg_het_scale_trial -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1
 stage_660 * !A
 ch4_young 1
 ch4_old 1
 cg_mean_cl * !A

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE !ASUV

ch4_g_day2_1v3 methane_per_mbw ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber mv !r us(Trait).ped(ANI_ID) diag(Trait !INIT 1.18589 0.00272633).ide(ANI_ID)
residual idh(cg_mean_cl).us(Trait).units

# NOTE: Reviewer-1 CG-heterogeneous-SCALE prototype (2026-09-20 follow-up, after sat(cg_mean_cl).us(Trait).units failed with 'Variance structure does not match data' -- several classes have as few as 4 records, too few for a full per-class covariance matrix): CH4 x CH4/MBW with idh(cg_mean_cl).us(Trait).units -- per-class residual SCALE, one SHARED trait correlation across all classes; discovery-only; do not generalise to key_bivariates_cg_het_scale unless this fit is stable and scientifically useful.
# Functional-syntax genetic term (us(Trait).ped(ANI_ID)), not classic bare
# Trait.ped(ANI_ID) -- functional syntax is used deliberately here
# to get ASReml's improved auto-initialisation for this parameter-
# rich CG-heterogeneous residual structure. This is NOT a claim that
# the classic bare form was tried and failed for this specific pair
# (untested) -- unlike bi_young_old, where that was actually
# confirmed. No !INIT values given for the genetic term since none
# apply cleanly to the classic-vs-functional distinction here.

VPREDICT !DEFINE
# Discovery-only VPREDICT: no derived quantities yet. Per
# ASReml-4.2-Functional-Specification.pdf Section 13.2, a bare
# VPREDICT !DEFINE + blank line reports every parameter's real
# name and number in the .pvc file -- read those off before
# writing any h2/SE block for this changed model structure.

