!WORKSPACE 5000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
bivariate_methane_mbw -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE

ch4_g_day2_1v3 Metabolic_BW ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber !r Trait.ped(ANI_ID) ide(ANI_ID)

1 2 1
0
Trait 0 US 10 0 0.96 !GP
Trait.ped(ANI_ID)
Trait 0 US 2 0 1.18 !GP
ANI_ID

VPREDICT !DEFINE
P Vp1 1 2 5
P Vp2 1 4 7
P Cp 3 6
H h2_1 5 Vp1
H h2_2 7 Vp2
R rg 5 6 7
R re 2 3 4
R cp Vp1 Cp Vp2
# MI=CH4/MBW (delta-method SE via ASReml VPREDICT, see composite_vpredict_specs)
P mia1 5 * 0.0020476511
P mia2 6 * -0.0033179877
P mia3 7 * 0.0013441062
P miVA mia1 + mia2 + mia3
P mip1 Vp1 * 0.0020476511
P mip2 Cp * -0.0033179877
P mip3 Vp2 * 0.0013441062
P miVP mip1 + mip2 + mip3
H mi_h2 miVA miVP
# RMTMBW (delta-method SE via ASReml VPREDICT, see composite_vpredict_specs)
P rtma1 5 * 1
P rtma2 6 * -1.5444
P rtma3 7 * 0.596293
P rtmVA rtma1 + rtma2 + rtma3
P rtmp1 Vp1 * 1
P rtmp2 Cp * -1.5444
P rtmp3 Vp2 * 0.596293
P rtmVP rtmp1 + rtmp2 + rtmp3
H rtm_h2 rtmVA rtmVP

