!WORKSPACE 12000 !CONTINUE !NODISPLAY !LOGFILE !MAXIT 300 !MP 2
trivariate_tri_methane_mbw_co2 -- generated by 01_generate_models.R
 ANI_ID !P
 ch4_g_day2_1v3 1
 co2_g_day2_1v3 1
 ch4_ratio 1
 methane_per_dmi 1
 methane_per_mbw 1
 Metabolic_BW 1
 SEX * !A
 TX 1
 BR 1
 SU 1
 CL 1
 CV 1
 LY 1
 UN 1
 het 1
 rec 1
 age_in_years 1
 ch4_GroupNumber * !A
 weight 1
 DMI 1
 adg 1
 methane_per_adg 1
 methane_per_rumen 1
 methane_per_muscle 1
 rumen 1
 age_in_months 1
 age_in_weeks 1
 REARING_RANK 1
 BIRTH_RANK 1
 ewe_birth_rank 1
 ewe_rearing_rank 1
 dam_parity_group_num 1
 ct_muscle_kg 1
 methane_per_lw 1
 ch4_adj_MBW 1
 ch4_adj_MBW_co2 1
 ch4_adj_DMI 1
 ch4_adj_adg 1
 adg_g 1
 stage_660 * !A
 ch4_young 1
 ch4_old 1
 cg_mean_cl * !A
 ch4_ratio_mol 1

pedigree.csv.SRT
phenotype_asreml.csv !SKIP 1 !MVINCLUDE

ch4_g_day2_1v3 Metabolic_BW co2_g_day2_1v3 ~ Trait Tr.SEX Tr.TX Tr.BR Tr.SU Tr.CL Tr.CV Tr.LY Tr.UN Tr.het Tr.rec Tr.REARING_RANK Tr.BIRTH_RANK Tr.ewe_birth_rank Tr.ewe_rearing_rank Tr.age_in_weeks Tr.dam_parity_group_num Tr.ch4_GroupNumber !r us(Trait !INIT 4.74938 2.45638 2.45206 176.62489 184.60582 20331.00000 !GP).ped(ANI_ID) diag(Trait !INIT 0.721556 1.702340 15712.200000).ide(ANI_ID)

# !INIT genetic values: pairwise-assembled (methane_mbw for CH4/MBW, methane_co2 for CO2;
# correlations from all three pairs); PE from the same fits. Residual auto-initialised.
# Parameters: 1-6 residual, 7-12 genetic, 13-15 PE (verify against the .pvc names).

VPREDICT !DEFINE
P Vp1 13 1 7
P Vp2 14 3 9
P Vp3 15 6 12
P C12 2 8
P C13 4 10
P C23 5 11
H h2_1 7 Vp1
H h2_2 9 Vp2
H h2_3 12 Vp3
R rg12 7 8 9
R rg13 7 10 12
R rg23 9 11 12
R re12 1 2 3
R re13 1 4 6
R re23 3 5 6
R rp12 Vp1 C12 Vp2
R rp13 Vp1 C13 Vp3
R rp23 Vp2 C23 Vp3

